### ISSUE TITLE
Add custom types with FFI

### ISSUE THREAD

**Issue by seanhandley** [StuartApp/h3_ruby#40]
https://www.varvet.com/blog/advanced-topics-in-ruby-ffi/#writing-our-own-data-types

This could be helpful in preventing some edge case misbehaviours. For instance, a lot of functions take a `resolution` argument as an integer but only accept values 0-15 (or produce undefined behaviour). e.g.

```ruby
irb(main):035:0> H3.h3_to_children(517700169958293503, 100000000)
Traceback (most recent call last):
        5: from /Users/sean/.rbenv/versions/2.5.0/bin/irb:11:in `<main>'
        4: from (irb):35
        3: from /Users/sean/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/h3-3.2.0/lib/h3/hierarchy.rb:51:in `h3_to_children'
        2: from /Users/sean/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/h3-3.2.0/lib/h3/hierarchy.rb:51:in `new'
        1: from /Users/sean/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/h3-3.2.0/lib/h3/hierarchy.rb:51:in `initialize'
NoMemoryError (too large allocation size)
```

In this case, we get told memory can't be allocated - which is ok.

```ruby
irb(main):036:0> H3.h3_to_children(517700169958293503, 1000000000)
Traceback (most recent call last):
        4: from /Users/sean/.rbenv/versions/2.5.0/bin/irb:11:in `<main>'
        3: from (irb):36
        2: from /Users/sean/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/h3-3.2.0/lib/h3/hierarchy.rb:52:in `h3_to_children'
        1: from /Users/sean/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/h3-3.2.0/lib/h3/hierarchy.rb:52:in `h3_to_children'
SystemStackError (stack level too deep)
```

Here we blow the stack, which is recoverable

```ruby
irb(main):037:0> H3.h3_to_children(517700169958293503, 10000000000)
Traceback (most recent call last):
        4: from /Users/sean/.rbenv/versions/2.5.0/bin/irb:11:in `<main>'
        3: from (irb):37
        2: from /Users/sean/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/h3-3.2.0/lib/h3/hierarchy.rb:50:in `h3_to_children'
        1: from /Users/sean/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/h3-3.2.0/lib/h3/hierarchy.rb:50:in `max_h3_to_children_size'
RangeError (integer 10000000000 too big to convert to `int')
```

Here FFI raises `RangeError` because the value is too large for a C integer.

```ruby
irb(main):039:0> H3.h3_to_children(613196570357137407, 1000)
Illegal instruction: 4
```

Now the real problem! We can crash the Ruby process like this 😱 

Setting up some custom types would give us a nice mechanism to validate this kind of data and prevent such nasty behaviour.

**Comment by seanhandley** [comment]
Tackled in #41
